	
	</div><!-- end content section -->
	
	<div class="clear_both"></div>
	
	<div id="footer">
		<p>
			&copy; <?php echo Date(Y);?> erikslist.com <br />   
			<span class="subtext">	
                       <a class="last" href="erikslist_rss.php">  Subscribe to RSS
                          <img style="vertical-align:text-bottom;" src="images/rss.jpg" height="15" width="15" alt="erikslist" />
                       </a>
			  
			</span>        
		</p>
	</div><!-- /footer -->

</div><!-- /page -->

</body>
</html>
